/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Car;
import model.Service;

/**
 *
 * @author hazel
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Car car;
    public CreateJPanel(Car car) {
        initComponents();
        this.car=car;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        lblTitle = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblEngineNo = new javax.swing.JLabel();
        lblSeatsNo = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblLicensePlates = new javax.swing.JLabel();
        lblWarrantyYear = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        lblOwnerTelNo = new javax.swing.JLabel();
        lblOwnerEmail = new javax.swing.JLabel();
        lblOwnerDriverLicense = new javax.swing.JLabel();
        lblOwnerSSN = new javax.swing.JLabel();
        lblOwnerAddress = new javax.swing.JLabel();
        lblServiceRecords = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtEngineNo = new javax.swing.JTextField();
        txtSeatsNo = new javax.swing.JTextField();
        txtLicensePlates = new javax.swing.JTextField();
        txtWarrantyYear = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtOwnerName = new javax.swing.JTextField();
        txtOwnerTelNo = new javax.swing.JTextField();
        txtOwnerEmail = new javax.swing.JTextField();
        txtOwnerDriverLicense = new javax.swing.JTextField();
        txtOwnerSSN = new javax.swing.JTextField();
        txtOwnerAddress = new javax.swing.JTextField();
        txtPhoto = new javax.swing.JTextField();
        btnupload = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblServiceName = new javax.swing.JLabel();
        lblServiceDate = new javax.swing.JLabel();
        lblServiceCost = new javax.swing.JLabel();
        txtServiceName = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        txtServiceCost = new javax.swing.JTextField();

        jTextField10.setText("jTextField10");

        setPreferredSize(new java.awt.Dimension(800, 800));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Cars");

        lblBrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBrand.setText("Brand");

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModel.setText("Model");

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblColor.setText("Color");

        lblEngineNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEngineNo.setText("Engine No.");

        lblSeatsNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeatsNo.setText("Seats No.");

        lblYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblYear.setText("Year");

        lblLicensePlates.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLicensePlates.setText("License Plates");

        lblWarrantyYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWarrantyYear.setText("Warranty Year");

        lblPhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhoto.setText("Photo");

        lblOwnerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerName.setText("Owner Name");

        lblOwnerTelNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerTelNo.setText("Owner Tel. No");

        lblOwnerEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerEmail.setText("Owner Email");

        lblOwnerDriverLicense.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerDriverLicense.setText("Owner Driver License");

        lblOwnerSSN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerSSN.setText("Owner SSN");

        lblOwnerAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOwnerAddress.setText("Owner Address");

        lblServiceRecords.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblServiceRecords.setText("Service Records");

        txtBrand.setName("brand"); // NOI18N
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtModel.setName("model"); // NOI18N
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtYear.setName("year"); // NOI18N
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        txtColor.setName("color"); // NOI18N
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        txtEngineNo.setName("engineNo"); // NOI18N
        txtEngineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEngineNoActionPerformed(evt);
            }
        });

        txtSeatsNo.setName("seatsNo"); // NOI18N

        txtLicensePlates.setName("licensePlates"); // NOI18N

        txtWarrantyYear.setName("warrantyYear"); // NOI18N

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtOwnerName.setName("ownerName"); // NOI18N

        txtOwnerTelNo.setName("ownerTelephoneNo"); // NOI18N

        txtOwnerEmail.setName("ownerEmailAddresses"); // NOI18N
        txtOwnerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerEmailActionPerformed(evt);
            }
        });

        txtOwnerDriverLicense.setName("ownerDriverLicense"); // NOI18N
        txtOwnerDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerDriverLicenseActionPerformed(evt);
            }
        });

        txtOwnerSSN.setName("ownerSocialSecurityNo"); // NOI18N
        txtOwnerSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerSSNActionPerformed(evt);
            }
        });

        txtOwnerAddress.setName("serviceRecords"); // NOI18N
        txtOwnerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerAddressActionPerformed(evt);
            }
        });

        txtPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoActionPerformed(evt);
            }
        });

        btnupload.setText("Upload");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        lblImage.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblServiceName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblServiceName.setText("Service Name");

        lblServiceDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblServiceDate.setText("Service Date");

        lblServiceCost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblServiceCost.setText("Service Cost");

        txtServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceNameActionPerformed(evt);
            }
        });

        txtServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDateActionPerformed(evt);
            }
        });

        txtServiceCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnupload)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnSave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblServiceRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblOwnerDriverLicense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(lblOwnerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOwnerTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblServiceCost)
                                    .addComponent(lblServiceDate)
                                    .addComponent(lblServiceName))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdd))
                                    .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(230, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblOwnerAddress, lblOwnerEmail, lblOwnerName, lblOwnerSSN, lblOwnerTelNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBrand, txtColor, txtEngineNo, txtLicensePlates, txtModel, txtOwnerAddress, txtOwnerDriverLicense, txtOwnerEmail, txtOwnerName, txtOwnerSSN, txtOwnerTelNo, txtPhoto, txtSeatsNo, txtWarrantyYear, txtYear});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblServiceCost, lblServiceDate, lblServiceName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModel)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOwnerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwnerSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwnerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOwnerTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWarrantyYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicensePlates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupload)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblServiceName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblServiceDate)
                                .addGap(15, 15, 15)
                                .addComponent(lblServiceCost)))
                        .addGap(35, 35, 35)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblServiceCost, lblServiceDate, lblServiceName, txtServiceCost, txtServiceDate, txtServiceName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBrand, txtColor, txtEngineNo, txtLicensePlates, txtModel, txtPhoto, txtSeatsNo, txtWarrantyYear, txtYear});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblOwnerAddress, lblOwnerDriverLicense, lblOwnerEmail, lblOwnerName, lblOwnerSSN, lblOwnerTelNo, txtOwnerAddress, txtOwnerDriverLicense, txtOwnerEmail, txtOwnerName, txtOwnerSSN, txtOwnerTelNo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtEngineNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEngineNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEngineNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String brand=txtBrand.getText();
        String model=txtModel.getText();
        String color=txtColor.getText();
        String year=txtYear.getText();
        String engine=txtEngineNo.getText();
        String seats=txtSeatsNo.getText();
        String licensePlate=txtLicensePlates.getText();
        String ownerName=txtOwnerName.getText();
        String ownerTelephoneNo= txtOwnerTelNo.getText();
        String ownerEmailAddresses = txtOwnerEmail.getText();
        String ownerDriverLicense =txtOwnerDriverLicense.getText();
        String ownerSocialSecurityNo = txtOwnerSSN.getText();
        String ownerAddress = txtOwnerAddress.getText();
        String warrantyYear = txtWarrantyYear.getText();
        String photoPath = txtPhoto.getText();
        
        if("".equals(seats) || "".equals(ownerDriverLicense)
                || "".equals(licensePlate) || "".equals(ownerName)
                || "".equals(ownerTelephoneNo) || "".equals(ownerEmailAddresses)
                || "".equals(engine)|| "".equals(brand) || "".equals(model)
                || "".equals(color) || "".equals(year) || "".equals(ownerSocialSecurityNo)
                || "".equals(ownerAddress) || "".equals(warrantyYear) || "".equals(photoPath)){
            JOptionPane.showMessageDialog(this,"Please Enter all details");
            return;
        }
        
        if(!isAlphaNumeric(brand.trim())){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid brand");
           return;
        }
        
        if(!isAlphaNumeric(model.trim())){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid model");
           return;
        }
        
        if(!isAlphabetic(color)){
            JOptionPane.showMessageDialog(this,"Error! Please enter valid color");
            return;
        }
        
        if(year.length()!=4 || !isNumeric(year)){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid year");
           return;
        }
        
        if(!isAlphaNumeric(engine) || engine.length()!=6 ){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid engine number");
           return;
        }
        
        if(!isNumeric(seats) || "0".equals(seats)){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid seat number");
           return;
        }
        
        if(!isAlphaNumeric(licensePlate) || licensePlate.length()<5 || licensePlate.length()>8 ){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid license plate number");
           return;
        }
        
        if(warrantyYear.length()!=4 || !isNumeric(warrantyYear)){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid warranty year");
           return;
        }
        
        if(!isAlphabetic(ownerName.trim())){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid owner name");
           return;
        }
        
        if(ownerTelephoneNo.length()!=10 || !isNumeric(ownerTelephoneNo) ){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid owner telephone");
           return;
        }
        
        if(!isValidEmail(ownerEmailAddresses)){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid email address");
           return;
        }
        
        if(!isAlphaNumeric(ownerDriverLicense) || ownerDriverLicense.length()>10){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid owner driver license no.");
           return;
        }
        
        if(!isNumeric(ownerSocialSecurityNo)|| ownerSocialSecurityNo.length()>9){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid SSN");
           return; 
        }
        
        if(!isAlphaNumeric(ownerAddress)){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid owner address");
           return;  
        }
        
        if(!photoPath.toLowerCase().contains(".png")){
           JOptionPane.showMessageDialog(this,"Error! Please enter valid image with acceptable format(.png)");
           return;  
        }
        
        
        
       
        car.setBrand(brand);
        car.setModel(model);
        car.setColor(color);
        car.setYear(year);
        car.setEngineNo(engine);
        car.setSeatsNo(seats);
        car.setLicensePlates(licensePlate);
        car.setOwnerName(ownerName);
        car.setOwnerTelephoneNo(ownerTelephoneNo);
        car.setOwnerEmailAddresses(ownerEmailAddresses);
        car.setOwnerDriverLicense(ownerDriverLicense);
        car.setOwnerSocialSecurityNo(ownerSocialSecurityNo);
        car.setOwnerAddress(ownerAddress);
        car.setWarrantyYear(warrantyYear);
        car.setPhotoPath(photoPath);
        car.setPhoto((ImageIcon) lblImage.getIcon());
        car.setRecords(serviceRecord);
        JOptionPane.showMessageDialog(this, "Success ! Car details saved successfully");
    }//GEN-LAST:event_btnSaveActionPerformed
   
    public static boolean isNumeric(String str) { 
      try {  
        Double.parseDouble(str);  
        return true;
      } catch(NumberFormatException e){  
        return false;  
      }  
    }
    
    public static boolean isAlphaNumeric(String s) {
        return s != null && s.matches("^[a-zA-Z0-9]*$");
    }
    
        
    public static boolean isValidEmail(String s){
        String regex = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(s);
        return matcher.matches();  
    }
    
    public static boolean isAlphabetic(String s) {
        return s != null && s.matches("^[a-zA-Z]*$");
    }
    
    public static boolean isValidDate(String date){
     try{
        SimpleDateFormat sd= new SimpleDateFormat("mm/dd/yyyy");
        sd.parse(date);
        return true;
    }catch(ParseException e){
        return false;
    }
   }

    private void txtOwnerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerEmailActionPerformed

    private void txtOwnerDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerDriverLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerDriverLicenseActionPerformed

    private void txtOwnerSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerSSNActionPerformed

    private void txtOwnerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerAddressActionPerformed

    private void txtPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        JFileChooser choose=new JFileChooser();
        choose.showOpenDialog(null);
        File f=choose.getSelectedFile();
        lblImage.setIcon(new ImageIcon(f.toString()));
        filename=f.getAbsolutePath();
        txtPhoto.setText(filename);
    }//GEN-LAST:event_btnuploadActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if("".equals(txtServiceName.getText())|| "".equals(txtServiceDate.getText()) || "".equals(txtServiceCost.getText())){
            JOptionPane.showMessageDialog(this,"Error ! Please enter service details");
            return;
        }
        
        if(!isAlphaNumeric(txtServiceName.getText().trim())){
            JOptionPane.showMessageDialog(this,"Error ! Please enter valid service name");
            return;
        }
        if(!isValidDate(txtServiceDate.getText())){
            JOptionPane.showMessageDialog(this,"Error ! Please enter valid date");
            return; 
        }
        if(!isNumeric(txtServiceCost.getText())){
            JOptionPane.showMessageDialog(this,"Error ! Please enter valid service cost");
            return;
        }
        Service service =new Service();
        service.setServiceName(txtServiceName.getText());
        service.setServiceDate(txtServiceDate.getText());
        service.setServiceCost(txtServiceCost.getText());
        serviceRecord.add(service);
        JOptionPane.showMessageDialog(this, "Success ! Service Record Added");   
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceNameActionPerformed

    private void txtServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDateActionPerformed

    private void txtServiceCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnupload;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicensePlates;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLicense;
    private javax.swing.JLabel lblOwnerEmail;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSSN;
    private javax.swing.JLabel lblOwnerTelNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSeatsNo;
    private javax.swing.JLabel lblServiceCost;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JLabel lblServiceName;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlates;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLicense;
    private javax.swing.JTextField txtOwnerEmail;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerSSN;
    private javax.swing.JTextField txtOwnerTelNo;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtSeatsNo;
    private javax.swing.JTextField txtServiceCost;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtServiceName;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
    byte[] photo=null;
    String filename=null;
    ArrayList<Service> serviceRecord=new ArrayList<>();
}
